### ISSUE TITLE
robot which is to automatically collect and feed a 3D-printer

### ISSUE THREAD

**Issue by Jost3dPrint** [dragondgold/octo-control#11]
Hey @mullinsen, I saw your video on YouTube (https://www.youtube.com/watch?v=JmpPQA_8aZc) and would like to build a robot like that. Do you have any documentation or anything else that could help me?
Kind regards Jost

**Comment by mullinsen** [comment]
Hello @Jost3dPrint!
I have attached our bachelor’s thesis, which should include all the information you need. 
However, especially with regards to the software, be aware that this thesis was our first encounter with Python - and multithreading - and consequently the software is very buggy. The video is made with a flattering edit:) I hope it still may provide you with a basis to build upon.
If I remember correctly the budget of the project was 5000 NOK, which is about 500€.
Good luck!

[Bachelor_2018.pdf](https://github.com/user-attachments/files/16319087/Bachelor_2018.pdf)

**Comment by Jost3dPrint** [comment]
Thank you very much, that helps me a lot :D
