### ISSUE TITLE
Using code in bachelor thesis

### ISSUE THREAD

**Issue by mullinsen** [dragondgold/octo-control#2]
Hi!
I would like to use this code in my bachelors thesis, in order to build a robot which is to automatically collect and feed a 3D-printer with print sheets whenever a print is done - in other words automating the 3D-printing process. Is it okay that I use large parts of this code in my project? This would be of great help for me and my group.
Best regards,
Michael

**Comment by dragondgold** [comment]
@mullinsen of course! Go ahead! Best wishes for the project, would love to see it running! :)

**Comment by mullinsen** [comment]
Thank you very much, I will try to remember to make a video to show you the final result when the time comes :)

**Comment by mullinsen** [comment]
https://www.youtube.com/watch?v=JmpPQA_8aZc
Quick video of the finished product, in case you would like to have a look.

**Comment by dragondgold** [comment]
Wow really amazing job!!!! Congrats, I love it :)
