### ISSUE TITLE
How do i use the programm? Changes: API key, the address and port?

### ISSUE THREAD

**Issue by Zuganfang** [dragondgold/octo-control#9]
Hello,

where in the code do i have to
Enter the API key, the address and port?

Is this the right way to run the programm?

1. git clone https://github.com/dragondgold/octo-control.git

2. sudo ./octocontrol.py --apikey 6F383070189C47E98A557D046D50596D --host 192.168.0.153 --port 5000 --send-gcode "G0 Z2 F100"

Sorry for my question, but I'm pretty new to the python game

Greetings

Tim

**Comment by dragondgold** [comment]
Hi @Zuganfang !

You are almost there! You need to run:

1. `git clone https://github.com/dragondgold/octo-control.git`
2. `python3 ./octo-control/octocontrol.py --apikey 6F383070189C47E98A557D046D50596D --host 192.168.0.153 --port 5000 --send-gcode "G0 Z2 F100"`

You need to install `python3` to use the script, on Ubuntu or Debian based systems you can usually do `sudo apt-get install python3` to install it!
